# Generated by Django 4.2.1 on 2024-03-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaffLogic', '0003_alter_newsmodel_article_user_and_more'),
        ('CustomerLogic', '0002_alter_ordersmodel_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaffLogic.routesmodel'),
        ),
    ]
