# Generated by Django 4.2.1 on 2024-03-20 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RoutesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Route_Destination_Airport', to='StaffLogic.airportmodel')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Route_Origin_Airport', to='StaffLogic.airportmodel')),
            ],
        ),
    ]
