# Generated by Django 4.2.1 on 2024-03-25 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StaffLogic', '0002_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='article_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routesmodel',
            name='destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Route_Destination_Airport', to='StaffLogic.airportmodel'),
        ),
        migrations.AlterField(
            model_name='routesmodel',
            name='origin_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Route_Origin_Airport', to='StaffLogic.airportmodel'),
        ),
    ]
